# Generated by Django 3.2.19 on 2023-07-10 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20230710_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='service.response'),
        ),
    ]
